In [2]:
import torch

In [3]:
a = torch.randn(5, 4, 3)
a.shape

torch.Size([5, 4, 3])

In [4]:
len(a)

5

In [1]:
N = 10

In [14]:
scales = torch.randn(N, 1)
eye = torch.eye(3).unsqueeze(0)  # (1, 3, 3)

In [15]:
scales, scales.shape

(tensor([[ 1.0062],
         [ 0.1491],
         [ 0.6687],
         [-0.2091],
         [ 0.5724],
         [-1.2750],
         [ 0.0496],
         [-0.1056],
         [ 0.4682],
         [-0.7143]]),
 torch.Size([10, 1]))

In [16]:
eye, eye.shape

(tensor([[[1., 0., 0.],
          [0., 1., 0.],
          [0., 0., 1.]]]),
 torch.Size([1, 3, 3]))

In [17]:
(scales**2).shape

torch.Size([10, 1])

In [21]:
(scales**2).unsqueeze(-1).shape

torch.Size([10, 1, 1])

In [19]:
eye

tensor([[[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]]])

In [22]:
(eye * (scales**2).unsqueeze(-1)).shape

torch.Size([10, 3, 3])

In [20]:
cov_3D = eye * (scales**2).unsqueeze(-1).unsqueeze(-1)  # (N, 3, 3)

In [23]:
cam = torch.randn(1, 3, 3)

In [24]:
cam.transpose(1, 2).shape

torch.Size([1, 3, 3])